### ISSUE TITLE
Python 2 or 3 ?

### ISSUE THREAD

**Issue by betegon** [vbelz/Speech-enhancement#4]
Hi, should we use python2.x or python 3.x in order to make it run?
I ask you because I am going through some issues installing the requirements and maybe it has to do with the python version.

Thanks for your work!

**Comment by betegon** [comment]
Problem solved using `Python 3.7`. Was it intended to use that version?

**Comment by vbelz** [comment]
Sure, good to hear it worked.

Le jeu. 5 mars 2020 à 09:40, Miguel Betegón <notifications@github.com> a
écrit :
